name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget cmake make gcc pkg-config libgtk-3-dev
          wget https://cmocka.org/files/1.1/cmocka-1.1.5.tar.xz
          tar -xf cmocka-1.1.5.tar.xz
          cd cmocka-1.1.5
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          sudo ldconfig

      - name: Build
        run: make

      - name: Run tests
        run: make test
